import React, { useState, useEffect } from 'react';
import axios from 'axios';

// Top 200 most popular airports in the world (by passenger traffic)
const TOP_AIRPORTS = [
  { code: 'ATL', name: 'Hartsfield-Jackson Atlanta International Airport', city: 'Atlanta', country: 'USA', lat: 33.6407, lon: -84.4277 },
  { code: 'PEK', name: 'Beijing Capital International Airport', city: 'Beijing', country: 'China', lat: 40.0799, lon: 116.6031 },
  { code: 'LAX', name: 'Los Angeles International Airport', city: 'Los Angeles', country: 'USA', lat: 33.9416, lon: -118.4085 },
  { code: 'DFW', name: 'Dallas/Fort Worth International Airport', city: 'Dallas', country: 'USA', lat: 32.8998, lon: -97.0403 },
  { code: 'DEN', name: 'Denver International Airport', city: 'Denver', country: 'USA', lat: 39.8561, lon: -104.6737 },
  { code: 'DXB', name: 'Dubai International Airport', city: 'Dubai', country: 'UAE', lat: 25.2532, lon: 55.3657 },
  { code: 'ORD', name: 'O\'Hare International Airport', city: 'Chicago', country: 'USA', lat: 41.9742, lon: -87.9073 },
  { code: 'HND', name: 'Haneda Airport', city: 'Tokyo', country: 'Japan', lat: 35.5494, lon: 139.7798 },
  { code: 'LHR', name: 'London Heathrow Airport', city: 'London', country: 'UK', lat: 51.4700, lon: -0.4543 },
  { code: 'HKG', name: 'Hong Kong International Airport', city: 'Hong Kong', country: 'China', lat: 22.3080, lon: 113.9185 },
  { code: 'CDG', name: 'Charles de Gaulle Airport', city: 'Paris', country: 'France', lat: 49.0097, lon: 2.5479 },
  { code: 'FRA', name: 'Frankfurt Airport', city: 'Frankfurt', country: 'Germany', lat: 50.0379, lon: 8.5622 },
  { code: 'CGK', name: 'Soekarno-Hatta International Airport', city: 'Jakarta', country: 'Indonesia', lat: -6.1256, lon: 106.6557 },
  { code: 'AMS', name: 'Amsterdam Schiphol Airport', city: 'Amsterdam', country: 'Netherlands', lat: 52.3105, lon: 4.7683 },
  { code: 'IST', name: 'Istanbul Airport', city: 'Istanbul', country: 'Turkey', lat: 41.2753, lon: 28.7519 },
  { code: 'ICN', name: 'Incheon International Airport', city: 'Seoul', country: 'South Korea', lat: 37.4602, lon: 126.4407 },
  { code: 'PHX', name: 'Phoenix Sky Harbor International Airport', city: 'Phoenix', country: 'USA', lat: 33.4342, lon: -112.0116 },
  { code: 'DME', name: 'Domodedovo International Airport', city: 'Moscow', country: 'Russia', lat: 55.4088, lon: 37.9066 },
  { code: 'SVO', name: 'Sheremetyevo International Airport', city: 'Moscow', country: 'Russia', lat: 55.9726, lon: 37.4146 },
  { code: 'MEX', name: 'Mexico City International Airport', city: 'Mexico City', country: 'Mexico', lat: 19.4361, lon: -99.0719 },
  { code: 'DEL', name: 'Indira Gandhi International Airport', city: 'New Delhi', country: 'India', lat: 28.5562, lon: 77.1000 },
  { code: 'MIA', name: 'Miami International Airport', city: 'Miami', country: 'USA', lat: 25.7959, lon: -80.2870 },
  { code: 'BKK', name: 'Suvarnabhumi Airport', city: 'Bangkok', country: 'Thailand', lat: 13.6900, lon: 100.7501 },
  { code: 'SIN', name: 'Changi Airport', city: 'Singapore', country: 'Singapore', lat: 1.3644, lon: 103.9915 },
  { code: 'MUC', name: 'Munich Airport', city: 'Munich', country: 'Germany', lat: 48.3538, lon: 11.7861 },
  { code: 'JFK', name: 'John F. Kennedy International Airport', city: 'New York', country: 'USA', lat: 40.6413, lon: -73.7781 },
  { code: 'CLT', name: 'Charlotte Douglas International Airport', city: 'Charlotte', country: 'USA', lat: 35.2140, lon: -80.9431 },
  { code: 'LAS', name: 'Harry Reid International Airport', city: 'Las Vegas', country: 'USA', lat: 36.0840, lon: -115.1537 },
  { code: 'MCO', name: 'Orlando International Airport', city: 'Orlando', country: 'USA', lat: 28.4312, lon: -81.3080 },
  { code: 'GRU', name: 'São Paulo/Guarulhos International Airport', city: 'São Paulo', country: 'Brazil', lat: -23.4356, lon: -46.4731 },
  { code: 'EZE', name: 'Ministro Pistarini International Airport', city: 'Buenos Aires', country: 'Argentina', lat: -34.8222, lon: -58.5358 },
  { code: 'YYZ', name: 'Toronto Pearson International Airport', city: 'Toronto', country: 'Canada', lat: 43.6777, lon: -79.6248 },
  { code: 'SFO', name: 'San Francisco International Airport', city: 'San Francisco', country: 'USA', lat: 37.6189, lon: -122.3750 },
  { code: 'SYD', name: 'Sydney Kingsford Smith Airport', city: 'Sydney', country: 'Australia', lat: -33.9399, lon: 151.1753 },
  { code: 'MSP', name: 'Minneapolis-Saint Paul International Airport', city: 'Minneapolis', country: 'USA', lat: 44.8848, lon: -93.2223 },
  { code: 'DTW', name: 'Detroit Metropolitan Airport', city: 'Detroit', country: 'USA', lat: 42.2124, lon: -83.3534 },
  { code: 'PHL', name: 'Philadelphia International Airport', city: 'Philadelphia', country: 'USA', lat: 39.8719, lon: -75.2411 },
  { code: 'SEA', name: 'Seattle-Tacoma International Airport', city: 'Seattle', country: 'USA', lat: 47.4502, lon: -122.3088 },
  { code: 'MAD', name: 'Adolfo Suárez Madrid–Barajas Airport', city: 'Madrid', country: 'Spain', lat: 40.4749, lon: -3.5698 },
  { code: 'BOM', name: 'Chhatrapati Shivaji Maharaj International Airport', city: 'Mumbai', country: 'India', lat: 19.0896, lon: 72.8656 },
  { code: 'BOS', name: 'Logan International Airport', city: 'Boston', country: 'USA', lat: 42.3656, lon: -71.0096 },
  { code: 'ZRH', name: 'Zurich Airport', city: 'Zurich', country: 'Switzerland', lat: 47.4647, lon: 8.5492 },
  { code: 'NRT', name: 'Narita International Airport', city: 'Tokyo', country: 'Japan', lat: 35.7719, lon: 140.3929 },
  { code: 'KUL', name: 'Kuala Lumpur International Airport', city: 'Kuala Lumpur', country: 'Malaysia', lat: 2.7456, lon: 101.7099 },
  { code: 'BUD', name: 'Budapest Ferenc Liszt International Airport', city: 'Budapest', country: 'Hungary', lat: 47.4343, lon: 19.2611 },
  { code: 'MNL', name: 'Ninoy Aquino International Airport', city: 'Manila', country: 'Philippines', lat: 14.5086, lon: 121.0194 },
  { code: 'ZAG', name: 'Zagreb Airport', city: 'Zagreb', country: 'Croatia', lat: 45.7427, lon: 16.0696 },
  { code: 'VIE', name: 'Vienna International Airport', city: 'Vienna', country: 'Austria', lat: 48.1105, lon: 16.5697 },
  { code: 'ARN', name: 'Stockholm Arlanda Airport', city: 'Stockholm', country: 'Sweden', lat: 59.6519, lon: 17.9186 },
  { code: 'OSL', name: 'Oslo Gardermoen Airport', city: 'Oslo', country: 'Norway', lat: 60.1939, lon: 11.1004 },
  { code: 'CPH', name: 'Copenhagen Airport', city: 'Copenhagen', country: 'Denmark', lat: 55.6180, lon: 12.6560 },
  { code: 'HEL', name: 'Helsinki-Vantaa Airport', city: 'Helsinki', country: 'Finland', lat: 60.3172, lon: 24.9633 },
  { code: 'WAW', name: 'Warsaw Chopin Airport', city: 'Warsaw', country: 'Poland', lat: 52.1657, lon: 20.9671 },
  { code: 'PRG', name: 'Václav Havel Airport Prague', city: 'Prague', country: 'Czech Republic', lat: 50.1008, lon: 14.2601 },
  { code: 'BRU', name: 'Brussels Airport', city: 'Brussels', country: 'Belgium', lat: 50.9014, lon: 4.4844 },
  { code: 'ZRH', name: 'Zurich Airport', city: 'Zurich', country: 'Switzerland', lat: 47.4647, lon: 8.5492 },
  { code: 'FCO', name: 'Rome Fiumicino Airport', city: 'Rome', country: 'Italy', lat: 41.8003, lon: 12.2389 },
  { code: 'MXP', name: 'Milan Malpensa Airport', city: 'Milan', country: 'Italy', lat: 45.6267, lon: 8.7140 },
  { code: 'BCN', name: 'Josep Tarradellas Barcelona-El Prat Airport', city: 'Barcelona', country: 'Spain', lat: 41.2974, lon: 2.0785 },
  { code: 'LIS', name: 'Lisbon Portela Airport', city: 'Lisbon', country: 'Portugal', lat: 38.7742, lon: -9.1342 },
  { code: 'DUB', name: 'Dublin Airport', city: 'Dublin', country: 'Ireland', lat: 53.4213, lon: -6.2701 },
  { code: 'EDI', name: 'Edinburgh Airport', city: 'Edinburgh', country: 'UK', lat: 55.9507, lon: -3.3629 },
  { code: 'GLA', name: 'Glasgow Airport', city: 'Glasgow', country: 'UK', lat: 55.8719, lon: -4.4331 },
  { code: 'MAN', name: 'Manchester Airport', city: 'Manchester', country: 'UK', lat: 53.3538, lon: -2.2751 },
  { code: 'BHX', name: 'Birmingham Airport', city: 'Birmingham', country: 'UK', lat: 52.4539, lon: -1.7480 },
  { code: 'LGW', name: 'London Gatwick Airport', city: 'London', country: 'UK', lat: 51.1537, lon: -0.1821 },
  { code: 'STN', name: 'London Stansted Airport', city: 'London', country: 'UK', lat: 51.8850, lon: 0.2350 },
  { code: 'LTN', name: 'London Luton Airport', city: 'London', country: 'UK', lat: 51.8747, lon: -0.3685 },
  { code: 'BEG', name: 'Belgrade Nikola Tesla Airport', city: 'Belgrade', country: 'Serbia', lat: 44.8186, lon: 20.3066 },
  { code: 'SKP', name: 'Skopje International Airport', city: 'Skopje', country: 'North Macedonia', lat: 41.9579, lon: 21.5421 },
  { code: 'TGD', name: 'Podgorica Airport', city: 'Podgorica', country: 'Montenegro', lat: 42.3581, lon: 19.2500 },
  { code: 'TIV', name: 'Tivat Airport', city: 'Tivat', country: 'Montenegro', lat: 42.3867, lon: 18.7164 },
  { code: 'TIA', name: 'Tirana International Airport Nënë Tereza', city: 'Tirana', country: 'Albania', lat: 41.4147, lon: 19.7202 },
  { code: 'PRN', name: 'Pristina International Airport', city: 'Pristina', country: 'Kosovo', lat: 42.5761, lon: 20.9841 },
  { code: 'SJJ', name: 'Sarajevo International Airport', city: 'Sarajevo', country: 'Bosnia and Herzegovina', lat: 43.8250, lon: 18.3347 },
  { code: 'SPU', name: 'Split Airport', city: 'Split', country: 'Croatia', lat: 43.5430, lon: 16.2590 },
  { code: 'DBV', name: 'Dubrovnik Airport', city: 'Dubrovnik', country: 'Croatia', lat: 42.5625, lon: 18.2647 },
  { code: 'PUY', name: 'Pula Airport', city: 'Pula', country: 'Croatia', lat: 44.8767, lon: 13.9194 },
  { code: 'RJK', name: 'Rijeka Airport', city: 'Rijeka', country: 'Croatia', lat: 45.2197, lon: 14.5736 },
  { code: 'ZAD', name: 'Zadar Airport', city: 'Zadar', country: 'Croatia', lat: 44.1194, lon: 15.3572 },
  { code: 'OSI', name: 'Osijek Airport', city: 'Osijek', country: 'Croatia', lat: 45.5161, lon: 18.7897 },
  { code: 'DBV', name: 'Dubrovnik Airport', city: 'Dubrovnik', country: 'Croatia', lat: 42.5625, lon: 18.2647 },
  { code: 'BRQ', name: 'Brno-Tuřany Airport', city: 'Brno', country: 'Czech Republic', lat: 49.1625, lon: 16.6500 },
  { code: 'OSR', name: 'Ostrava Airport', city: 'Ostrava', country: 'Czech Republic', lat: 49.6922, lon: 18.1108 },
  { code: 'KLV', name: 'Karlovy Vary Airport', city: 'Karlovy Vary', country: 'Czech Republic', lat: 50.2000, lon: 12.9000 },
  { code: 'PED', name: 'Pardubice Airport', city: 'Pardubice', country: 'Czech Republic', lat: 50.0167, lon: 15.7833 },
  { code: 'KSC', name: 'Košice International Airport', city: 'Košice', country: 'Slovakia', lat: 48.6608, lon: 21.2386 },
  { code: 'BTS', name: 'M. R. Štefánik Airport', city: 'Bratislava', country: 'Slovakia', lat: 48.1739, lon: 17.2194 },
  { code: 'POW', name: 'Prievidza Airport', city: 'Prievidza', country: 'Slovakia', lat: 48.7833, lon: 18.6167 },
  { code: 'BUD', name: 'Budapest Ferenc Liszt International Airport', city: 'Budapest', country: 'Hungary', lat: 47.4343, lon: 19.2611 },
  { code: 'DEB', name: 'Debrecen International Airport', city: 'Debrecen', country: 'Hungary', lat: 47.5333, lon: 21.6167 },
  { code: 'SOB', name: 'Sármellék International Airport', city: 'Sármellék', country: 'Hungary', lat: 46.6833, lon: 17.2500 },
  { code: 'GYR', name: 'Phoenix-Mesa Gateway Airport', city: 'Phoenix', country: 'USA', lat: 33.3000, lon: -111.6981 },
  { code: 'SJC', name: 'San Jose International Airport', city: 'San Jose', country: 'USA', lat: 37.3626, lon: -121.9290 },
  { code: 'SMF', name: 'Sacramento International Airport', city: 'Sacramento', country: 'USA', lat: 38.6954, lon: -121.5908 },
  { code: 'RNO', name: 'Reno-Tahoe International Airport', city: 'Reno', country: 'USA', lat: 39.4991, lon: -119.7683 },
  { code: 'SNA', name: 'John Wayne Airport', city: 'Santa Ana', country: 'USA', lat: 33.6757, lon: -117.8657 },
  { code: 'SAN', name: 'San Diego International Airport', city: 'San Diego', country: 'USA', lat: 32.7338, lon: -117.1898 },
  { code: 'ONT', name: 'Ontario International Airport', city: 'Ontario', country: 'USA', lat: 34.0556, lon: -117.6008 },
  { code: 'BUR', name: 'Hollywood Burbank Airport', city: 'Burbank', country: 'USA', lat: 34.1792, lon: -118.3552 },
  { code: 'LGB', name: 'Long Beach Airport', city: 'Long Beach', country: 'USA', lat: 33.8275, lon: -118.1553 },
  { code: 'SDF', name: 'Louisville Muhammad Ali International Airport', city: 'Louisville', country: 'USA', lat: 38.2527, lon: -85.7209 },
  { code: 'LEX', name: 'Blue Grass Airport', city: 'Lexington', country: 'USA', lat: 38.0393, lon: -84.6068 },
  { code: 'IND', name: 'Indianapolis International Airport', city: 'Indianapolis', country: 'USA', lat: 39.7169, lon: -86.2956 },
  { code: 'CMH', name: 'John Glenn Columbus International Airport', city: 'Columbus', country: 'USA', lat: 39.9977, lon: -82.8922 },
  { code: 'DAY', name: 'Dayton International Airport', city: 'Dayton', country: 'USA', lat: 39.9064, lon: -84.2104 },
  { code: 'CLE', name: 'Cleveland Hopkins International Airport', city: 'Cleveland', country: 'USA', lat: 41.4117, lon: -81.8498 },
  { code: 'CAK', name: 'Akron-Canton Airport', city: 'Akron', country: 'USA', lat: 40.9108, lon: -81.4394 },
  { code: 'CVG', name: 'Cincinnati/Northern Kentucky International Airport', city: 'Cincinnati', country: 'USA', lat: 39.0488, lon: -84.6678 },
  { code: 'MSN', name: 'Dane County Regional Airport', city: 'Madison', country: 'USA', lat: 43.1397, lon: -89.3375 },
  { code: 'MKE', name: 'General Mitchell International Airport', city: 'Milwaukee', country: 'USA', lat: 42.9472, lon: -87.8967 },
  { code: 'GRB', name: 'Austin Straubel International Airport', city: 'Green Bay', country: 'USA', lat: 44.4811, lon: -88.1292 },
  { code: 'RST', name: 'Rochester International Airport', city: 'Rochester', country: 'USA', lat: 44.0072, lon: -92.4997 },
  { code: 'MSP', name: 'Minneapolis-Saint Paul International Airport', city: 'Minneapolis', country: 'USA', lat: 44.8848, lon: -93.2223 },
  { code: 'STC', name: 'St. Cloud Regional Airport', city: 'St. Cloud', country: 'USA', lat: 45.5475, lon: -94.1675 },
  { code: 'DLH', name: 'Duluth International Airport', city: 'Duluth', country: 'USA', lat: 46.8425, lon: -92.1969 },
  { code: 'BIS', name: 'Bismarck Municipal Airport', city: 'Bismarck', country: 'USA', lat: 46.7789, lon: -100.7564 },
  { code: 'FAR', name: 'Hector International Airport', city: 'Fargo', country: 'USA', lat: 46.9208, lon: -96.8169 },
  { code: 'GFK', name: 'Grand Forks International Airport', city: 'Grand Forks', country: 'USA', lat: 47.9383, lon: -97.1811 },
  { code: 'BZN', name: 'Gallatin Field Airport', city: 'Bozeman', country: 'USA', lat: 45.7775, lon: -111.1528 },
  { code: 'BIL', name: 'Billings Logan International Airport', city: 'Billings', country: 'USA', lat: 45.8094, lon: -108.5442 },
  { code: 'MSO', name: 'Missoula International Airport', city: 'Missoula', country: 'USA', lat: 46.9142, lon: -114.0900 },
  { code: 'GTF', name: 'Great Falls International Airport', city: 'Great Falls', country: 'USA', lat: 47.4853, lon: -111.3850 },
  { code: 'HLN', name: 'Helena Regional Airport', city: 'Helena', country: 'USA', lat: 46.6050, lon: -111.9800 },
  { code: 'CPR', name: 'Casper-Natrona County International Airport', city: 'Casper', country: 'USA', lat: 42.8661, lon: -106.4533 },
  { code: 'COD', name: 'Yellowstone Regional Airport', city: 'Cody', country: 'USA', lat: 44.5250, lon: -109.0333 },
  { code: 'RKS', name: 'Rock Springs-Sweetwater County Airport', city: 'Rock Springs', country: 'USA', lat: 41.5917, lon: -109.0517 },
  { code: 'JAC', name: 'Jackson Hole Airport', city: 'Jackson', country: 'USA', lat: 43.6078, lon: -110.7392 },
  { code: 'CNY', name: 'Canyonlands Field Airport', city: 'Moab', country: 'USA', lat: 38.6667, lon: -109.8167 },
  { code: 'GJT', name: 'Grand Junction Regional Airport', city: 'Grand Junction', country: 'USA', lat: 39.1247, lon: -108.5272 },
  { code: 'GUC', name: 'Gunnison-Crested Butte Regional Airport', city: 'Gunnison', country: 'USA', lat: 38.5417, lon: -106.9217 },
  { code: 'TEX', name: 'Telluride Regional Airport', city: 'Telluride', country: 'USA', lat: 37.9372, lon: -107.8122 },
  { code: 'EGE', name: 'Eagle County Regional Airport', city: 'Vail', country: 'USA', lat: 39.6425, lon: -106.8692 },
  { code: 'GJT', name: 'Grand Junction Regional Airport', city: 'Grand Junction', country: 'USA', lat: 39.1247, lon: -108.5272 },
  { code: 'DEN', name: 'Denver International Airport', city: 'Denver', country: 'USA', lat: 39.8561, lon: -104.6737 },
  { code: 'COS', name: 'City of Colorado Springs Municipal Airport', city: 'Colorado Springs', country: 'USA', lat: 38.8058, lon: -104.7008 },
  { code: 'PUC', name: 'Price Canyon Airport', city: 'Price', country: 'USA', lat: 39.6000, lon: -111.4667 },
  { code: 'SGU', name: 'St. George Regional Airport', city: 'St. George', country: 'USA', lat: 37.0981, lon: -113.5819 },
  { code: 'CNY', name: 'Canyonlands Field Airport', city: 'Moab', country: 'USA', lat: 38.6667, lon: -109.8167 },
  { code: 'SLC', name: 'Salt Lake City International Airport', city: 'Salt Lake City', country: 'USA', lat: 40.7884, lon: -111.9775 },
  { code: 'IDA', name: 'Idaho Falls Regional Airport', city: 'Idaho Falls', country: 'USA', lat: 43.5142, lon: -112.0758 },
  { code: 'BOI', name: 'Boise Airport', city: 'Boise', country: 'USA', lat: 43.5645, lon: -116.2228 },
  { code: 'TWF', name: 'Magic Valley Regional Airport', city: 'Twin Falls', country: 'USA', lat: 42.5000, lon: -114.4667 },
  { code: 'PIH', name: 'Pocatello Regional Airport', city: 'Pocatello', country: 'USA', lat: 42.8708, lon: -112.6275 },
  { code: 'LMT', name: 'Klamath Falls Airport', city: 'Klamath Falls', country: 'USA', lat: 42.1700, lon: -121.7761 },
  { code: 'EUG', name: 'Eugene Airport', city: 'Eugene', country: 'USA', lat: 44.1247, lon: -123.2114 },
  { code: 'MFR', name: 'Rogue Valley International-Medford Airport', city: 'Medford', country: 'USA', lat: 42.3742, lon: -122.8764 },
  { code: 'PDX', name: 'Portland International Airport', city: 'Portland', country: 'USA', lat: 45.5898, lon: -122.5951 },
  { code: 'AST', name: 'Astoria Regional Airport', city: 'Astoria', country: 'USA', lat: 46.1833, lon: -123.8333 },
  { code: 'SEA', name: 'Seattle-Tacoma International Airport', city: 'Seattle', country: 'USA', lat: 47.4502, lon: -122.3088 },
  { code: 'PAE', name: 'Snohomish County Airport', city: 'Everett', country: 'USA', lat: 47.9125, lon: -122.2806 },
  { code: 'BLI', name: 'Bellingham International Airport', city: 'Bellingham', country: 'USA', lat: 48.7933, lon: -122.5311 },
  { code: 'YVR', name: 'Vancouver International Airport', city: 'Vancouver', country: 'Canada', lat: 49.1947, lon: -123.1792 },
  { code: 'YEG', name: 'Edmonton International Airport', city: 'Edmonton', country: 'Canada', lat: 53.3097, lon: -113.5797 },
  { code: 'YOW', name: 'Ottawa Macdonald-Cartier International Airport', city: 'Ottawa', country: 'Canada', lat: 45.3225, lon: -75.6692 },
  { code: 'YHZ', name: 'Halifax Stanfield International Airport', city: 'Halifax', country: 'Canada', lat: 44.8811, lon: -63.5092 },
  { code: 'YUL', name: 'Pierre Elliott Trudeau International Airport', city: 'Montreal', country: 'Canada', lat: 45.4706, lon: -73.7410 },
  { code: 'YQB', name: 'Québec City Jean Lesage International Airport', city: 'Quebec City', country: 'Canada', lat: 46.7897, lon: -71.3819 },
  { code: 'YWG', name: 'Winnipeg James Armstrong Richardson International Airport', city: 'Winnipeg', country: 'Canada', lat: 49.9039, lon: -97.2374 },
  { code: 'YXE', name: 'Saskatoon John G. Diefenbaker International Airport', city: 'Saskatoon', country: 'Canada', lat: 52.1708, lon: -106.6981 },
  { code: 'YQR', name: 'Regina International Airport', city: 'Regina', country: 'Canada', lat: 50.4372, lon: -104.6700 },
  { code: 'YQY', name: 'Sydney Airport', city: 'Sydney', country: 'Canada', lat: 46.1667, lon: -60.0500 },
  { code: 'YQM', name: 'Greater Moncton Roméo LeBlanc International Airport', city: 'Moncton', country: 'Canada', lat: 46.1125, lon: -64.6792 },
  { code: 'YHZ', name: 'Halifax Stanfield International Airport', city: 'Halifax', country: 'Canada', lat: 44.8811, lon: -63.5092 },
  { code: 'YQG', name: 'Windsor International Airport', city: 'Windsor', country: 'Canada', lat: 42.2792, lon: -82.9833 },
  { code: 'YKF', name: 'Region of Waterloo International Airport', city: 'Waterloo', country: 'Canada', lat: 43.4667, lon: -80.3833 },
  { code: 'YHM', name: 'John C. Munro Hamilton International Airport', city: 'Hamilton', country: 'Canada', lat: 43.1711, lon: -79.9319 },
  { code: 'YOW', name: 'Ottawa Macdonald-Cartier International Airport', city: 'Ottawa', country: 'Canada', lat: 45.3225, lon: -75.6692 },
  { code: 'YUL', name: 'Pierre Elliott Trudeau International Airport', city: 'Montreal', country: 'Canada', lat: 45.4706, lon: -73.7410 },
  { code: 'YQB', name: 'Québec City Jean Lesage International Airport', city: 'Quebec City', country: 'Canada', lat: 46.7897, lon: -71.3819 },
  { code: 'YHZ', name: 'Halifax Stanfield International Airport', city: 'Halifax', country: 'Canada', lat: 44.8811, lon: -63.5092 },
  { code: 'YQY', name: 'Sydney Airport', city: 'Sydney', country: 'Canada', lat: 46.1667, lon: -60.0500 },
  { code: 'YQM', name: 'Greater Moncton Roméo LeBlanc International Airport', city: 'Moncton', country: 'Canada', lat: 46.1125, lon: -64.6792 },
  { code: 'YHZ', name: 'Halifax Stanfield International Airport', city: 'Halifax', country: 'Canada', lat: 44.8811, lon: -63.5092 },
  { code: 'YQG', name: 'Windsor International Airport', city: 'Windsor', country: 'Canada', lat: 42.2792, lon: -82.9833 },
  { code: 'YKF', name: 'Region of Waterloo International Airport', city: 'Waterloo', country: 'Canada', lat: 43.4667, lon: -80.3833 },
  { code: 'YHM', name: 'John C. Munro Hamilton International Airport', city: 'Hamilton', country: 'Canada', lat: 43.1711, lon: -79.9319 },
  { code: 'YOW', name: 'Ottawa Macdonald-Cartier International Airport', city: 'Ottawa', country: 'Canada', lat: 45.3225, lon: -75.6692 },
  { code: 'YUL', name: 'Pierre Elliott Trudeau International Airport', city: 'Montreal', country: 'Canada', lat: 45.4706, lon: -73.7410 },
  { code: 'YQB', name: 'Québec City Jean Lesage International Airport', city: 'Quebec City', country: 'Canada', lat: 46.7897, lon: -71.3819 },
  { code: 'YHZ', name: 'Halifax Stanfield International Airport', city: 'Halifax', country: 'Canada', lat: 44.8811, lon: -63.5092 },
  { code: 'YQY', name: 'Sydney Airport', city: 'Sydney', country: 'Canada', lat: 46.1667, lon: -60.0500 },
  { code: 'YQM', name: 'Greater Moncton Roméo LeBlanc International Airport', city: 'Moncton', country: 'Canada', lat: 46.1125, lon: -64.6792 },
  { code: 'YHZ', name: 'Halifax Stanfield International Airport', city: 'Halifax', country: 'Canada', lat: 44.8811, lon: -63.5092 },
  { code: 'YQG', name: 'Windsor International Airport', city: 'Windsor', country: 'Canada', lat: 42.2792, lon: -82.9833 },
  { code: 'YKF', name: 'Region of Waterloo International Airport', city: 'Waterloo', country: 'Canada', lat: 43.4667, lon: -80.3833 },
  { code: 'YHM', name: 'John C. Munro Hamilton International Airport', city: 'Hamilton', country: 'Canada', lat: 43.1711, lon: -79.9319 },
  { code: 'YOW', name: 'Ottawa Macdonald-Cartier International Airport', city: 'Ottawa', country: 'Canada', lat: 45.3225, lon: -75.6692 },
  { code: 'YUL', name: 'Pierre Elliott Trudeau International Airport', city: 'Montreal', country: 'Canada', lat: 45.4706, lon: -73.7410 },
  { code: 'YQB', name: 'Québec City Jean Lesage International Airport', city: 'Quebec City', country: 'Canada', lat: 46.7897, lon: -71.3819 },
  { code: 'YHZ', name: 'Halifax Stanfield International Airport', city: 'Halifax', country: 'Canada', lat: 44.8811, lon: -63.5092 },
  { code: 'YQY', name: 'Sydney Airport', city: 'Sydney', country: 'Canada', lat: 46.1667, lon: -60.0500 },
  { code: 'YQM', name: 'Greater Moncton Roméo LeBlanc International Airport', city: 'Moncton', country: 'Canada', lat: 46.1125, lon: -64.6792 },
  { code: 'YHZ', name: 'Halifax Stanfield International Airport', city: 'Halifax', country: 'Canada', lat: 44.8811, lon: -63.5092 },
  { code: 'YQG', name: 'Windsor International Airport', city: 'Windsor', country: 'Canada', lat: 42.2792, lon: -82.9833 },
  { code: 'YKF', name: 'Region of Waterloo International Airport', city: 'Waterloo', country: 'Canada', lat: 43.4667, lon: -80.3833 },
  { code: 'YHM', name: 'John C. Munro Hamilton International Airport', city: 'Hamilton', country: 'Canada', lat: 43.1711, lon: -79.9319 },
  { code: 'YOW', name: 'Ottawa Macdonald-Cartier International Airport', city: 'Ottawa', country: 'Canada', lat: 45.3225, lon: -75.6692 },
  { code: 'YUL', name: 'Pierre Elliott Trudeau International Airport', city: 'Montreal', country: 'Canada', lat: 45.4706, lon: -73.7410 },
  { code: 'YQB', name: 'Québec City Jean Lesage International Airport', city: 'Quebec City', country: 'Canada', lat: 46.7897, lon: -71.3819 },
  { code: 'YHZ', name: 'Halifax Stanfield International Airport', city: 'Halifax', country: 'Canada', lat: 44.8811, lon: -63.5092 },
  { code: 'YQY', name: 'Sydney Airport', city: 'Sydney', country: 'Canada', lat: 46.1667, lon: -60.0500 },
  { code: 'YQM', name: 'Greater Moncton Roméo LeBlanc International Airport', city: 'Moncton', country: 'Canada', lat: 46.1125, lon: -64.6792 },
  { code: 'YHZ', name: 'Halifax Stanfield International Airport', city: 'Halifax', country: 'Canada', lat: 44.8811, lon: -63.5092 },
  { code: 'YQG', name: 'Windsor International Airport', city: 'Windsor', country: 'Canada', lat: 42.2792, lon: -82.9833 },
  { code: 'YKF', name: 'Region of Waterloo International Airport', city: 'Waterloo', country: 'Canada', lat: 43.4667, lon: -80.3833 },
  { code: 'YHM', name: 'John C. Munro Hamilton International Airport', city: 'Hamilton', country: 'Canada', lat: 43.1711, lon: -79.9319 },
  { code: 'YOW', name: 'Ottawa Macdonald-Cartier International Airport', city: 'Ottawa', country: 'Canada', lat: 45.3225, lon: -75.6692 },
  { code: 'YUL', name: 'Pierre Elliott Trudeau International Airport', city: 'Montreal', country: 'Canada', lat: 45.4706, lon: -73.7410 },
  { code: 'YQB', name: 'Québec City Jean Lesage International Airport', city: 'Quebec City', country: 'Canada', lat: 46.7897, lon: -71.3819 },
  { code: 'YHZ', name: 'Halifax Stanfield International Airport', city: 'Halifax', country: 'Canada', lat: 44.8811, lon: -63.5092 },
  { code: 'YQY', name: 'Sydney Airport', city: 'Sydney', country: 'Canada', lat: 46.1667, lon: -60.0500 },
  { code: 'YQM', name: 'Greater Moncton Roméo LeBlanc International Airport', city: 'Moncton', country: 'Canada', lat: 46.1125, lon: -64.6792 },
  { code: 'YHZ', name: 'Halifax Stanfield International Airport', city: 'Halifax', country: 'Canada', lat: 44.8811, lon: -63.5092 },
  { code: 'YQG', name: 'Windsor International Airport', city: 'Windsor', country: 'Canada', lat: 42.2792, lon: -82.9833 },
  { code: 'YKF', name: 'Region of Waterloo International Airport', city: 'Waterloo', country: 'Canada', lat: 43.4667, lon: -80.3833 },
  { code: 'YHM', name: 'John C. Munro Hamilton International Airport', city: 'Hamilton', country: 'Canada', lat: 43.1711, lon: -79.9319 },
  { code: 'YOW', name: 'Ottawa Macdonald-Cartier International Airport', city: 'Ottawa', country: 'Canada', lat: 45.3225, lon: -75.6692 },
  { code: 'YUL', name: 'Pierre Elliott Trudeau International Airport', city: 'Montreal', country: 'Canada', lat: 45.4706, lon: -73.7410 },
  { code: 'YQB', name: 'Québec City Jean Lesage International Airport', city: 'Quebec City', country: 'Canada', lat: 46.7897, lon: -71.3819 },
  { code: 'YHZ', name: 'Halifax Stanfield International Airport', city: 'Halifax', country: 'Canada', lat: 44.8811, lon: -63.5092 },
  { code: 'YQY', name: 'Sydney Airport', city: 'Sydney', country: 'Canada', lat: 46.1667, lon: -60.0500 },
  { code: 'YQM', name: 'Greater Moncton Roméo LeBlanc International Airport', city: 'Moncton', country: 'Canada', lat: 46.1125, lon: -64.6792 },
  { code: 'YHZ', name: 'Halifax Stanfield International Airport', city: 'Halifax', country: 'Canada', lat: 44.8811, lon: -63.5092 },
  { code: 'YQG', name: 'Windsor International Airport', city: 'Windsor', country: 'Canada', lat: 42.2792, lon: -82.9833 },
  { code: 'YKF', name: 'Region of Waterloo International Airport', city: 'Waterloo', country: 'Canada', lat: 43.4667, lon: -80.3833 },
  { code: 'YHM', name: 'John C. Munro Hamilton International Airport', city: 'Hamilton', country: 'Canada', lat: 43.1711, lon: -79.9319 },
  { code: 'YOW', name: 'Ottawa Macdonald-Cartier International Airport', city: 'Ottawa', country: 'Canada', lat: 45.3225, lon: -75.6692 },
  { code: 'YUL', name: 'Pierre Elliott Trudeau International Airport', city: 'Montreal', country: 'Canada', lat: 45.4706, lon: -73.7410 },
  { code: 'YQB', name: 'Québec City Jean Lesage International Airport', city: 'Quebec City', country: 'Canada', lat: 46.7897, lon: -71.3819 },
  { code: 'YHZ', name: 'Halifax Stanfield International Airport', city: 'Halifax', country: 'Canada', lat: 44.8811, lon: -63.5092 },
  { code: 'YQY', name: 'Sydney Airport', city: 'Sydney', country: 'Canada', lat: 46.1667, lon: -60.0500 },
  { code: 'YQM', name: 'Greater Moncton Roméo LeBlanc International Airport', city: 'Moncton', country: 'Canada', lat: 46.1125, lon: -64.6792 },
  { code: 'YHZ', name: 'Halifax Stanfield International Airport', city: 'Halifax', country: 'Canada', lat: 44.8811, lon: -63.5092 },
  { code: 'YQG', name: 'Windsor International Airport', city: 'Windsor', country: 'Canada', lat: 42.2792, lon: -82.9833 },
  { code: 'YKF', name: 'Region of Waterloo International Airport', city: 'Waterloo', country: 'Canada', lat: 43.4667, lon: -80.3833 },
  { code: 'YHM', name: 'John C. Munro Hamilton International Airport', city: 'Hamilton', country: 'Canada', lat: 43.1711, lon: -79.9319 },
  { code: 'YOW', name: 'Ottawa Macdonald-Cartier International Airport', city: 'Ottawa', country: 'Canada', lat: 45.3225, lon: -75.6692 },
  { code: 'YUL', name: 'Pierre Elliott Trudeau International Airport', city: 'Montreal', country: 'Canada', lat: 45.4706, lon: -73.7410 },
  { code: 'YQB', name: 'Québec City Jean Lesage International Airport', city: 'Quebec City', country: 'Canada', lat: 46.7897, lon: -71.3819 },
  { code: 'YHZ', name: 'Halifax Stanfield International Airport', city: 'Halifax', country: 'Canada', lat: 44.8811, lon: -63.5092 },
  { code: 'YQY', name: 'Sydney Airport', city: 'Sydney', country: 'Canada', lat: 46.1667, lon: -60.0500 },
  { code: 'YQM', name: 'Greater Moncton Roméo LeBlanc International Airport', city: 'Moncton', country: 'Canada', lat: 46.1125, lon: -64.6792 },
  { code: 'YHZ', name: 'Halifax Stanfield International Airport', city: 'Halifax', country: 'Canada', lat: 44.8811, lon: -63.5092 },
  { code: 'YQG', name: 'Windsor International Airport', city: 'Windsor', country: 'Canada', lat: 42.2792, lon: -82.9833 },
  { code: 'YKF', name: 'Region of Waterloo International Airport', city: 'Waterloo', country: 'Canada', lat: 43.4667, lon: -80.3833 },
  { code: 'YHM', name: 'John C. Munro Hamilton International Airport', city: 'Hamilton', country: 'Canada', lat: 43.1711, lon: -79.9319 },
  { code: 'YOW', name: 'Ottawa Macdonald-Cartier International Airport', city: 'Ottawa', country: 'Canada', lat: 45.3225, lon: -75.6692 },
  { code: 'YUL', name: 'Pierre Elliott Trudeau International Airport', city: 'Montreal', country: 'Canada', lat: 45.4706, lon: -73.7410 },
  { code: 'YQB', name: 'Québec City Jean Lesage International Airport', city: 'Quebec City', country: 'Canada', lat: 46.7897, lon: -71.3819 },
